account/urls.py
from django.urls import path
from account.views import (
    ProfileUpdateService,
    UserCreateService,
    UserCreateView,
    AccountsListView,
    DashBoardProfileView,
    LoginView,
    LogoutView,
    UsersListView,
    AccountCreateService,
    AccountCreateView,
    ProfileUpdateView,
    AccountsMeView,
    AccountUpdateStatusService,
)

app_name = "account"

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashBoardProfileView.as_view(), name="dashboard"),
    path("manager/accounts/", AccountsListView.as_view(), name="account_list"),
    path("manager/account/create/", AccountCreateView.as_view(), name="create_account"),
    path("manager/users/", UsersListView.as_view(), name="user_list"),
    path("manager/users/create", UserCreateView.as_view(), name="create_user"),
    path("accounts/me/", AccountsMeView.as_view(), name="account_me"),
    path("user/about/", ProfileUpdateView.as_view(), name="update_about"),
    path("api/users/", UserCreateService.as_view(), name="user_service"),
    path("api/accounts/", AccountCreateService.as_view(), name="account_service"),
    path(
        "api/accounts/<int:pk>/active/",
        AccountUpdateStatusService.as_view(),
        name="account_active",
    ),
    path(
        "api/users/update/", ProfileUpdateService.as_view(), name="update_about_service"
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("", include("tree.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard.html
{% extends 'extends.html' %}
{% load static %}
{% block navbar %} {% include 'components/navbar.html' %} {% endblock %}

{% block content %}
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        {% include 'components/dashboard_nav.html' %}
    </div>
</div>
{% endblock content %}

templates/extends.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Home {% endblock title %} </title>

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/sweetalert2.min.css' %}" rel="stylesheet">
</head>

<body>
    {% block navbar %} {% endblock %}

    {% block content %} {% endblock %}
    {% block footer %} {% endblock %}
    {% block dependecies %}
    {% include 'components/dependencies.html' %}
    {% endblock %}



</body>

</html>

templates/login.html
{% extends 'extends.html' %}
{% load static %}

{% block content %}

<div class="container-fluid pt-5">
    <div class="text-center">
        <h2 class="section-title px-5 mt-3 mb-3"><span class="px-2">Login</span></h2>
    </div>
    <div class="d-flex justify-content-center">
        <form class="col-lg-4" action="{% url 'account:login' %}" method="POST">
            {% csrf_token %}
            <div class="control-group">
                <label class="form-label">Nome de usuario</label>
                <input type="username" class="form-control" id="username" placeholder="Digite seu nome de usuario" name="username" required="required" />
                <p class="help-block text-danger"></p>
            </div>
            <div class="control-group">
                <label class="form-label">Senha</label>
                <input type="password" class="form-control" id="password" placeholder="Sua senha" name="password" required="required" />
                <p class="help-block text-danger"></p>
            </div>
            <button class="btn btn-primary col-12" type=" submit">Entrar</button>
        </form>
    </div>
</div>


{% endblock content %}

{% block dependencies %}
{% include 'components/dependecies.html' %}

{% endblock %}