account/urls.py
from django.urls import path
from account.views import (
    ProfileUpdateService,
    UserCreateService,
    UserCreateView,
    AccountsListView,
    DashBoardProfileView,
    LoginView,
    LogoutView,
    UsersListView,
    AccountCreateService,
    AccountCreateView,
    ProfileUpdateView,
    AccountsMeView,
    AccountUpdateStatusService,
)

app_name = "account"

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashBoardProfileView.as_view(), name="dashboard"),
    path("manager/accounts/", AccountsListView.as_view(), name="account_list"),
    path("manager/account/create/", AccountCreateView.as_view(), name="create_account"),
    path("manager/users/", UsersListView.as_view(), name="user_list"),
    path("manager/users/create", UserCreateView.as_view(), name="create_user"),
    path("accounts/me/", AccountsMeView.as_view(), name="account_me"),
    path("user/about/", ProfileUpdateView.as_view(), name="update_about"),
    path("api/users/", UserCreateService.as_view(), name="user_service"),
    path("api/accounts/", AccountCreateService.as_view(), name="account_service"),
    path(
        "api/accounts/<int:pk>/active/",
        AccountUpdateStatusService.as_view(),
        name="account_active",
    ),
    path(
        "api/users/update/", ProfileUpdateService.as_view(), name="update_about_service"
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("", include("tree.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tree/urls.py
from django.urls import path
from tree import views

app_name = "tree"

urlpatterns = [
    path("manager/plants", views.PlantListView.as_view(), name="list_plant"),
    path(
        "manager/plants/<int:pk>/details/",
        views.PlantDetailsView.as_view(),
        name="details_plant",
    ),
    path("manager/plants/create", views.PlantCreateView.as_view(), name="create_plant"),
    path(
        "manager/tree/create", views.PlatedTreeCreateView.as_view(), name="tree_create"
    ),
    path(
        "accounts/<int:pk>/tree/",
        views.PlantedTreeByAccountView.as_view(),
        name="tree_by_accounts",
    ),
    path("tree/me", views.PlatedTreeUserView.as_view(), name="tree_me"),
    path(
        "api/tree/me/",
        views.PlatedTreeUserViewService.as_view(),
        name="tree_me_service",
    ),
    path("api/plant/", views.PlantCreateService.as_view(), name="plant_service"),
    path("api/tree", views.PlatedTreeCreateService.as_view(), name="tree_service"),
]

templates/components/dashboard_nav.html
<div class="col-lg-3">
    <div class="card border-secondary">
        <div class="card-header bg-secondary border-0">
            <h4 class="font-weight-semi-bold m-0">
                <a href="{% url 'account:dashboard' %}">Dashboard</a>
            </h4>
        </div>
        <div class="card-body">

            <h5 class="font-weight-medium mb-3">Contas</h5>
            {% if request.user.is_superuser %}
            <div class="d-flex">
                <a href="{% url 'account:create_account' %}">Criar Conta</a>
            </div>
            <div class="d-flex">
                <a href="{% url 'account:account_list' %}">Contas</a>
            </div>
            {% else %}
            <div class="d-flex">
                <a href="{% url 'account:account_me' %}">Minhas Contas</a>
            </div>
            {% endif %}
            <hr class="mt-1">
            <h5 class="font-weight-medium mb-3">Plantas</h5>
            {% if request.user.is_superuser %}
            <div class="d-flex">
                <a href="{% url 'tree:list_plant' %}">Plantas</a>
            </div>
            <div class="d-flex">
                <a href="{% url 'tree:create_plant' %}">Criar Plantas</a>
            </div>
            {% else %}
            <div class="d-flex">
                <a href="{% url 'tree:tree_create' %}">Adicionar Planta</a>
            </div>
            <div class="d-flex">
                <a href="{% url 'tree:tree_me' %}">Minhas Plantas</a>
            </div>
            {% endif %}

            <hr class="mt-1">

            {% if request.user.is_superuser %}
            <h5 class="font-weight-medium mb-3">Usuários</h5>
            <div class="d-flex">
                <a href="{% url 'account:create_user' %}">Criar Usuário</a>
            </div>

            <div class="d-flex">
                <a href="{% url 'account:user_list' %}">Usuários</a>
            </div>
            <hr class="mt-1">
            {% endif %}
            <h5 class="font-weight-medium mb-3">Perfil</h5>
            <div class="d-flex">
                <a href="{% url 'account:update_about' %}">Editar perfil</a>
            </div>
        </div>
    </div>
</div>

templates/components/dependencies.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>

templates/components/footer.html
{% load static %}

<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
            </a>
            <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="" method="POST" id="form-newsletter">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" name="name" class="form-control border-0 py-4 input-newsletter-name" placeholder="Seu nome" required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" name="email" class="form-control border-0 py-4 input-newsletter-email" placeholder="Seu e-mail" required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Assine agora</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                by
                <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->

templates/components/navbar.html
<!-- Navbar Start -->
<div class="container-fluid">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="{% url 'account:dashboard' %}" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Trees Everywhere</h6>
            </a>

        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Contas</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                {% for account in accounts %}
                                <a href="{% url 'tree:tree_by_accounts' account.id %}" class="dropdown-item">{{account.name}}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="navbar-nav ml-auto py-0">

                        {% if request.user.is_authenticated %}
                        <a href="{% url 'account:logout' %}" class="nav-item nav-link">

                            <i class="fas fa-chevron-circle-right text-primary "></i>
                            <span class="badge">Sair</span>
                        </a>
                        {% endif %}

                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>