core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("", include("tree.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tree/urls.py
from django.urls import path
from tree import views

app_name = "tree"

urlpatterns = [
    path("manager/plants", views.PlantListView.as_view(), name="list_plant"),
    path(
        "manager/plants/<int:pk>/details/",
        views.PlantDetailsView.as_view(),
        name="details_plant",
    ),
    path("manager/plants/create", views.PlantCreateView.as_view(), name="create_plant"),
    path(
        "manager/tree/create", views.PlatedTreeCreateView.as_view(), name="tree_create"
    ),
    path(
        "accounts/<int:pk>/tree/",
        views.PlantedTreeByAccountView.as_view(),
        name="tree_by_accounts",
    ),
    path("tree/me", views.PlatedTreeUserView.as_view(), name="tree_me"),
    path(
        "api/tree/me/",
        views.PlatedTreeUserViewService.as_view(),
        name="tree_me_service",
    ),
    path("api/plant/", views.PlantCreateService.as_view(), name="plant_service"),
    path("api/tree", views.PlatedTreeCreateService.as_view(), name="tree_service"),
]

templates/plants/plant_create.html
{% extends 'extends.html' %}
{% load static %}

{% block navbar %} {% include 'components/navbar.html' %} {% endblock %}


{% block content %}

<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        {% block dashboard_nav %} {% include 'components/dashboard_nav.html' %} {% endblock %}
        <div class="col-lg-9 table-responsive mb-5">
            <form id="form-plant-create" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" name="name" class="form-control">
                </div>

                <div class="form-group">
                    <label for="scientific_name">Nome Científico</label>
                    <input type="text" name="scientific_name" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Adicionar Planta</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}


{% block dependecies %}
{% include 'components/dependencies.html' %}
<script src="{% static 'js/services/plant.js' %}"></script>

{% endblock %}

templates/plants/plant_details.html
{% extends 'extends.html' %}
{% load static %}
{% block navbar %} {% include 'components/navbar.html' %} {% endblock %}


{% block content %}
<div class="container-fluid pt-3">
    <div class="row px-xl-5">
        {% block dashboard_nav %} {% include 'components/dashboard_nav.html' %} {% endblock %}
        <div class="col-lg-9 table-responsive mb-5">

            {% if plants %}
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>ID</th>
                        <th>Usuário</th>
                        <th>Conta</th>
                        <th>Idade</th>
                        <th>Data de plantio</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for plant in plants %}
                    <tr>
                        <td class="align-middle">{{plant.id}}</td>
                        <td class="align-middle">{{plant.user.first_name}}</td>
                        <td class="align-middle">{{plant.account.name}}</td>
                        <td class="align-middle">{{plant.age}}</td>
                        <td class="align-middle">{{plant.plated_at|date:"d M, Y"}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <h4 class="m-0">Ainda não foram plantadas</h4>

            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}


{% block dependecies %}
{% include 'components/dependencies.html' %}
<script src="{% static 'js/services/plant.js' %}"></script>
{% endblock %}

templates/plants/plant_table.html
{% extends 'extends.html' %}
{% load static %}
{% block navbar %} {% include 'components/navbar.html' %} {% endblock %}


{% block content %}
<div class="container-fluid pt-3">
    <div class="row px-xl-5">
        {% block dashboard_nav %} {% include 'components/dashboard_nav.html' %} {% endblock %}
        <div class="col-lg-9 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Nome Científico</th>
                        <th>Detalhes</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for plant in plants %}
                    <tr>
                        <td class="align-middle">{{plant.id}}</td>
                        <td class="align-middle">{{plant.name}}</td>
                        <td class="align-middle">{{plant.scientific_name}}</td>
                        <td class="align-middle">
                            <a href="{% url 'tree:details_plant' plant.id %}"><i class="fa fa-eye"></i></a>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}


{% block dependecies %}
{% include 'components/dependencies.html' %}
<script src="{% static 'js/services/plant.js' %}"></script>
{% endblock %}

templates/plants/plants_by_accounts.html
{% extends 'extends.html' %}
{% load static %}
{% block navbar %} {% include 'components/navbar.html' %} {% endblock %}


{% block content %}
<div class="container-fluid pt-3">
    <div class="row px-xl-5">
        {% block dashboard_nav %} {% include 'components/dashboard_nav.html' %} {% endblock %}
        <div class="col-lg-9 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Nome Científico</th>
                        <th>Idade</th>
                        <th>Data de plantio</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for tree in trees %}
                    <tr>
                        <td class="align-middle">{{tree.id}}</td>
                        <td class="align-middle">{{tree.plant.name}}</td>
                        <td class="align-middle">{{tree.plant.scientific_name}}</td>
                        <td class="align-middle">{{tree.age}}</td>
                        <td class="align-middle">{{tree.plated_at|date:"d M, Y"}}</td>
                        <td class="align-middle">{{tree.latitude}}</td>
                        <td class="align-middle">{{tree.longitude}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}


{% block dependecies %}
{% include 'components/dependencies.html' %}
<script src="{% static 'js/services/plant.js' %}"></script>
{% endblock %}